/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedCompetitionsIndexRouteImport } from './routes/_authenticated/competitions/index'
import { Route as AuthenticatedCompetitionsIdRouteImport } from './routes/_authenticated/competitions/$id'
import { Route as AuthenticatedPaymentsIndexRouteImport } from './routes/_authenticated/payments/index'
import { Route as AuthenticatedPlayersIndexRouteImport } from './routes/_authenticated/players/index'
import { Route as AuthenticatedRefundsIndexRouteImport } from './routes/_authenticated/refunds/index'
import { Route as AuthenticatedResultReviewsIndexRouteImport } from './routes/_authenticated/result-reviews/index'
import { Route as AuthenticatedResultReviewsIdRouteImport } from './routes/_authenticated/result-reviews/$id'
import { Route as AuthenticatedStaffIndexRouteImport } from './routes/_authenticated/staff/index'
import { Route as AuthenticatedStrikesIndexRouteImport } from './routes/_authenticated/strikes/index'
import { Route as AuthenticatedVerificationsIndexRouteImport } from './routes/_authenticated/verifications/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompetitionsIndexRoute =
  AuthenticatedCompetitionsIndexRouteImport.update({
    id: '/competitions/',
    path: '/competitions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCompetitionsIdRoute =
  AuthenticatedCompetitionsIdRouteImport.update({
    id: '/competitions/$id',
    path: '/competitions/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPaymentsIndexRoute =
  AuthenticatedPaymentsIndexRouteImport.update({
    id: '/payments/',
    path: '/payments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlayersIndexRoute =
  AuthenticatedPlayersIndexRouteImport.update({
    id: '/players/',
    path: '/players/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRefundsIndexRoute =
  AuthenticatedRefundsIndexRouteImport.update({
    id: '/refunds/',
    path: '/refunds/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResultReviewsIndexRoute =
  AuthenticatedResultReviewsIndexRouteImport.update({
    id: '/result-reviews/',
    path: '/result-reviews/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResultReviewsIdRoute =
  AuthenticatedResultReviewsIdRouteImport.update({
    id: '/result-reviews/$id',
    path: '/result-reviews/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStaffIndexRoute = AuthenticatedStaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStrikesIndexRoute =
  AuthenticatedStrikesIndexRouteImport.update({
    id: '/strikes/',
    path: '/strikes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVerificationsIndexRoute =
  AuthenticatedVerificationsIndexRouteImport.update({
    id: '/verifications/',
    path: '/verifications/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/competitions/$id': typeof AuthenticatedCompetitionsIdRoute
  '/result-reviews/$id': typeof AuthenticatedResultReviewsIdRoute
  '/competitions/': typeof AuthenticatedCompetitionsIndexRoute
  '/payments/': typeof AuthenticatedPaymentsIndexRoute
  '/players/': typeof AuthenticatedPlayersIndexRoute
  '/refunds/': typeof AuthenticatedRefundsIndexRoute
  '/result-reviews/': typeof AuthenticatedResultReviewsIndexRoute
  '/staff/': typeof AuthenticatedStaffIndexRoute
  '/strikes/': typeof AuthenticatedStrikesIndexRoute
  '/verifications/': typeof AuthenticatedVerificationsIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/competitions/$id': typeof AuthenticatedCompetitionsIdRoute
  '/result-reviews/$id': typeof AuthenticatedResultReviewsIdRoute
  '/competitions': typeof AuthenticatedCompetitionsIndexRoute
  '/payments': typeof AuthenticatedPaymentsIndexRoute
  '/players': typeof AuthenticatedPlayersIndexRoute
  '/refunds': typeof AuthenticatedRefundsIndexRoute
  '/result-reviews': typeof AuthenticatedResultReviewsIndexRoute
  '/staff': typeof AuthenticatedStaffIndexRoute
  '/strikes': typeof AuthenticatedStrikesIndexRoute
  '/verifications': typeof AuthenticatedVerificationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/competitions/$id': typeof AuthenticatedCompetitionsIdRoute
  '/_authenticated/result-reviews/$id': typeof AuthenticatedResultReviewsIdRoute
  '/_authenticated/competitions/': typeof AuthenticatedCompetitionsIndexRoute
  '/_authenticated/payments/': typeof AuthenticatedPaymentsIndexRoute
  '/_authenticated/players/': typeof AuthenticatedPlayersIndexRoute
  '/_authenticated/refunds/': typeof AuthenticatedRefundsIndexRoute
  '/_authenticated/result-reviews/': typeof AuthenticatedResultReviewsIndexRoute
  '/_authenticated/staff/': typeof AuthenticatedStaffIndexRoute
  '/_authenticated/strikes/': typeof AuthenticatedStrikesIndexRoute
  '/_authenticated/verifications/': typeof AuthenticatedVerificationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/competitions/$id'
    | '/result-reviews/$id'
    | '/competitions/'
    | '/payments/'
    | '/players/'
    | '/refunds/'
    | '/result-reviews/'
    | '/staff/'
    | '/strikes/'
    | '/verifications/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/competitions/$id'
    | '/result-reviews/$id'
    | '/competitions'
    | '/payments'
    | '/players'
    | '/refunds'
    | '/result-reviews'
    | '/staff'
    | '/strikes'
    | '/verifications'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(auth)/sign-in'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/competitions/$id'
    | '/_authenticated/result-reviews/$id'
    | '/_authenticated/competitions/'
    | '/_authenticated/payments/'
    | '/_authenticated/players/'
    | '/_authenticated/refunds/'
    | '/_authenticated/result-reviews/'
    | '/_authenticated/staff/'
    | '/_authenticated/strikes/'
    | '/_authenticated/verifications/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authSignInRoute: typeof authSignInRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/competitions/': {
      id: '/_authenticated/competitions/'
      path: '/competitions'
      fullPath: '/competitions/'
      preLoaderRoute: typeof AuthenticatedCompetitionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/competitions/$id': {
      id: '/_authenticated/competitions/$id'
      path: '/competitions/$id'
      fullPath: '/competitions/$id'
      preLoaderRoute: typeof AuthenticatedCompetitionsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments/': {
      id: '/_authenticated/payments/'
      path: '/payments'
      fullPath: '/payments/'
      preLoaderRoute: typeof AuthenticatedPaymentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/players/': {
      id: '/_authenticated/players/'
      path: '/players'
      fullPath: '/players/'
      preLoaderRoute: typeof AuthenticatedPlayersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/refunds/': {
      id: '/_authenticated/refunds/'
      path: '/refunds'
      fullPath: '/refunds/'
      preLoaderRoute: typeof AuthenticatedRefundsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/result-reviews/': {
      id: '/_authenticated/result-reviews/'
      path: '/result-reviews'
      fullPath: '/result-reviews/'
      preLoaderRoute: typeof AuthenticatedResultReviewsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/result-reviews/$id': {
      id: '/_authenticated/result-reviews/$id'
      path: '/result-reviews/$id'
      fullPath: '/result-reviews/$id'
      preLoaderRoute: typeof AuthenticatedResultReviewsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff/': {
      id: '/_authenticated/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof AuthenticatedStaffIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/strikes/': {
      id: '/_authenticated/strikes/'
      path: '/strikes'
      fullPath: '/strikes/'
      preLoaderRoute: typeof AuthenticatedStrikesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/verifications/': {
      id: '/_authenticated/verifications/'
      path: '/verifications'
      fullPath: '/verifications/'
      preLoaderRoute: typeof AuthenticatedVerificationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCompetitionsIdRoute: typeof AuthenticatedCompetitionsIdRoute
  AuthenticatedResultReviewsIdRoute: typeof AuthenticatedResultReviewsIdRoute
  AuthenticatedCompetitionsIndexRoute: typeof AuthenticatedCompetitionsIndexRoute
  AuthenticatedPaymentsIndexRoute: typeof AuthenticatedPaymentsIndexRoute
  AuthenticatedPlayersIndexRoute: typeof AuthenticatedPlayersIndexRoute
  AuthenticatedRefundsIndexRoute: typeof AuthenticatedRefundsIndexRoute
  AuthenticatedResultReviewsIndexRoute: typeof AuthenticatedResultReviewsIndexRoute
  AuthenticatedStaffIndexRoute: typeof AuthenticatedStaffIndexRoute
  AuthenticatedStrikesIndexRoute: typeof AuthenticatedStrikesIndexRoute
  AuthenticatedVerificationsIndexRoute: typeof AuthenticatedVerificationsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCompetitionsIdRoute: AuthenticatedCompetitionsIdRoute,
  AuthenticatedResultReviewsIdRoute: AuthenticatedResultReviewsIdRoute,
  AuthenticatedCompetitionsIndexRoute: AuthenticatedCompetitionsIndexRoute,
  AuthenticatedPaymentsIndexRoute: AuthenticatedPaymentsIndexRoute,
  AuthenticatedPlayersIndexRoute: AuthenticatedPlayersIndexRoute,
  AuthenticatedRefundsIndexRoute: AuthenticatedRefundsIndexRoute,
  AuthenticatedResultReviewsIndexRoute: AuthenticatedResultReviewsIndexRoute,
  AuthenticatedStaffIndexRoute: AuthenticatedStaffIndexRoute,
  AuthenticatedStrikesIndexRoute: AuthenticatedStrikesIndexRoute,
  AuthenticatedVerificationsIndexRoute: AuthenticatedVerificationsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authSignInRoute: authSignInRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
