BEGIN;
DROP TABLE IF EXISTS outbox_events;
DROP TABLE IF EXISTS audit_events;
DROP TABLE IF EXISTS idempotency_keys;
DROP TABLE IF EXISTS disputes;
DROP TABLE IF EXISTS result_confirmations;
DROP TABLE IF EXISTS result_submissions;
DROP TABLE IF EXISTS matches;
DROP TABLE IF EXISTS competition_stages;
DROP TABLE IF EXISTS entry_members;
DROP TABLE IF EXISTS competition_entries;
DROP TABLE IF EXISTS competitions;
DROP TABLE IF EXISTS game_accounts;
DROP TABLE IF EXISTS games;
DROP TABLE IF EXISTS organization_members;
DROP TABLE IF EXISTS organizations;
DROP TABLE IF EXISTS player_profiles;
DROP TABLE IF EXISTS users;
COMMIT;
