package bracket

import (
	"fmt"
	"sort"
	"strings"
	"testing"
)

// Tests for the double elimination emitter.
//
// Everything here is a property rather than a stored expected graph, with two
// deliberate exceptions: the per-round match counts for power-of-two fields and
// one spot check of the drop mapping for a 16 entrant draw. A hardcoded 63
// match graph would be unreadable and would have to be regenerated by the very
// code it is meant to check.
//
// The heavier assertions come from deSimulate, which plays a draw out under a
// fixed pseudo-random outcome vector and then checks the things that only exist
// once players are moving through the edges: that everyone accumulates exactly
// two losses, that nobody plays twice in one round, and that a player dropping
// out of the winners bracket is not immediately handed the opponent they just
// beat.
//
// Every identifier in this file is prefixed de so it cannot collide with the
// single elimination or round robin test files.

// ---------------------------------------------------------------------------
// fixtures
// ---------------------------------------------------------------------------

func deEntries(count int) []DrawEntry {
	entries := make([]DrawEntry, count)
	for position := range entries {
		entries[position] = DrawEntry{
			EntryID: fmt.Sprintf("e%04d", position+1),
			SeedKey: position + 1,
		}
	}
	return entries
}

func deDraw(count int) DrawInput {
	return DrawInput{Format: DoubleElimination, Entries: deEntries(count)}
}

func deEmit(t *testing.T, count int) Graph {
	t.Helper()
	graph, err := Emit(deDraw(count))
	if err != nil {
		t.Fatalf("Emit(%d entries): %v", count, err)
	}
	return graph
}

// deSizes is every field size from 2 to 64, which covers every awkward
// non-power-of-two below the point where the shapes start repeating, plus a
// scatter of larger ones including both sides of each power of two and the
// MaxEntries ceiling.
var deSizes = func() []int {
	sizes := make([]int, 0, 80)
	for count := 2; count <= 64; count++ {
		sizes = append(sizes, count)
	}
	return append(sizes, 65, 66, 100, 127, 128, 129, 200, 255, 256, 257, 511, 512, 513, 1000, 1023, 1024)
}()

func deNode(t *testing.T, graph Graph, ref LocalRef) Node {
	t.Helper()
	for _, node := range graph.Nodes {
		if node.Ref == ref {
			return node
		}
	}
	t.Fatalf("graph has no match %s", ref)
	return Node{}
}

func deSlotKey(slot Slot) string {
	var builder strings.Builder
	writeSlot(&builder, slot)
	return builder.String()
}

func dePairKey(left, right string) [2]string {
	if left > right {
		left, right = right, left
	}
	return [2]string{left, right}
}

// deLosersRoundSize is the expected match count of a losers round for a winners
// bracket of 2^rounds positions, stated independently of the emitter.
func deLosersRoundSize(rounds, round int) int {
	if round%2 == 0 {
		return 1 << (rounds - 1 - round/2)
	}
	return 1 << (rounds - 2 - (round-1)/2)
}

// ---------------------------------------------------------------------------
// shape and invariants
// ---------------------------------------------------------------------------

// TestDoubleEliminationValidates is the headline check: for every field size the
// full Emit pipeline (emit, Prune, Rank) produces a graph Validate accepts, with
// no bye left anywhere and exactly the number of matches the format requires.
//
// 2n-1 comes from the loss accounting. Each of the n-1 eliminated players
// absorbs two losses and every played match produces exactly one loss, so a
// tournament in which the winners bracket finalist never loses runs 2n-2
// matches. The reset is the single extra match in the graph, unplayed in that
// case, which puts the node count at 2n-1 regardless of how the byes fell.
func TestDoubleEliminationValidates(t *testing.T) {
	for _, count := range deSizes {
		t.Run(fmt.Sprintf("n=%d", count), func(t *testing.T) {
			graph := deEmit(t, count)

			if err := Validate(graph); err != nil {
				t.Fatalf("Validate: %v", err)
			}
			if got, want := len(graph.Nodes), 2*count-1; got != want {
				t.Fatalf("match count = %d, want %d", got, want)
			}
			if graph.Format != DoubleElimination {
				t.Fatalf("format = %q", graph.Format)
			}

			for _, node := range graph.Nodes {
				switch node.Ref.Bracket {
				case BracketWinners, BracketLosers, BracketGrandFinal:
				default:
					t.Fatalf("%s: unexpected bracket %q", node.Ref, node.Ref.Bracket)
				}
				if node.Ref.Round < 1 || node.Ref.Number < 1 {
					t.Fatalf("%s: non-positive round or number", node.Ref)
				}
				if node.Rank < 1 {
					t.Fatalf("%s: rank %d", node.Ref, node.Rank)
				}
				if node.GroupKey != "" {
					t.Fatalf("%s: group key %q on a knockout match", node.Ref, node.GroupKey)
				}
				for side, slot := range map[string]Slot{"home": node.Home, "away": node.Away} {
					if slot.Kind == SourceBye || slot.Kind == SourceEmpty {
						t.Fatalf("%s: %s slot is %s after pruning", node.Ref, side, slot.Kind)
					}
				}
				if deSlotKey(node.Home) == deSlotKey(node.Away) {
					t.Fatalf("%s: both slots read %s", node.Ref, deSlotKey(node.Home))
				}
			}
		})
	}
}

// TestDoubleEliminationEntriesAppearOnce checks the entry vector is used exactly
// once and in full. In an elimination format an entrant is named directly by
// precisely one match, their first, and everything after that is an edge.
func TestDoubleEliminationEntriesAppearOnce(t *testing.T) {
	for _, count := range deSizes {
		t.Run(fmt.Sprintf("n=%d", count), func(t *testing.T) {
			in := deDraw(count)
			graph := deEmit(t, count)

			seen := make(map[string]int, count)
			for _, node := range graph.Nodes {
				for _, slot := range []Slot{node.Home, node.Away} {
					if slot.Kind == SourceEntry {
						seen[slot.EntryID]++
					}
				}
			}
			if len(seen) != count {
				t.Fatalf("%d distinct entries placed, want %d", len(seen), count)
			}
			for _, entry := range in.Entries {
				if seen[entry.EntryID] != 1 {
					t.Fatalf("entry %s placed %d times, want 1", entry.EntryID, seen[entry.EntryID])
				}
			}
		})
	}
}

// TestDoubleEliminationPowerOfTwoShape pins the round structure where no pruning
// happens, so the raw emitter shape is visible: k winners rounds halving from
// 2^(k-1), then 2k-2 losers rounds alternating minor and major, then two grand
// finals.
func TestDoubleEliminationPowerOfTwoShape(t *testing.T) {
	for rounds := 1; rounds <= 7; rounds++ {
		size := 1 << rounds
		t.Run(fmt.Sprintf("n=%d", size), func(t *testing.T) {
			graph := deEmit(t, size)

			counts := make(map[LocalRef]int)
			perRound := make(map[[2]int]int)
			brackets := map[string][]int{}
			for _, node := range graph.Nodes {
				counts[node.Ref]++
				if counts[node.Ref] > 1 {
					t.Fatalf("%s appears twice", node.Ref)
				}
				key := [2]int{0, node.Ref.Round}
				switch node.Ref.Bracket {
				case BracketWinners:
					key[0] = 0
				case BracketLosers:
					key[0] = 1
				default:
					key[0] = 2
				}
				perRound[key]++
				brackets[node.Ref.Bracket] = append(brackets[node.Ref.Bracket], node.Ref.Round)
			}

			for round := 1; round <= rounds; round++ {
				if got, want := perRound[[2]int{0, round}], size>>round; got != want {
					t.Fatalf("winners round %d has %d matches, want %d", round, got, want)
				}
			}
			if perRound[[2]int{0, rounds + 1}] != 0 {
				t.Fatalf("winners bracket has a round %d", rounds+1)
			}

			losersRounds := 0
			if rounds >= 2 {
				losersRounds = 2*rounds - 2
			}
			for round := 1; round <= losersRounds; round++ {
				if got, want := perRound[[2]int{1, round}], deLosersRoundSize(rounds, round); got != want {
					t.Fatalf("losers round %d has %d matches, want %d", round, got, want)
				}
			}
			if perRound[[2]int{1, losersRounds + 1}] != 0 {
				t.Fatalf("losers bracket has a round %d, want %d rounds", losersRounds+1, losersRounds)
			}
			if _, has := brackets[BracketLosers]; has != (rounds >= 2) {
				t.Fatalf("losers bracket present = %v for a %d entrant draw", has, size)
			}

			if got := perRound[[2]int{2, 1}]; got != 1 {
				t.Fatalf("grand final round 1 has %d matches, want 1", got)
			}
			if got := perRound[[2]int{2, 2}]; got != 1 {
				t.Fatalf("grand final round 2 has %d matches, want 1", got)
			}
			if got := perRound[[2]int{2, 3}]; got != 0 {
				t.Fatalf("grand final has a round 3")
			}
		})
	}
}

// TestDoubleEliminationEdges walks the raw emitter output, before Prune, and
// checks the edge set directly: every reference resolves, nothing points at
// itself, and no match's winner or loser is consumed twice. That last one is
// match_slots_one_consumer_uidx, and checking it pre-prune matters because Prune
// can only preserve uniqueness, never repair it.
func TestDoubleEliminationEdges(t *testing.T) {
	for _, count := range deSizes {
		t.Run(fmt.Sprintf("n=%d", count), func(t *testing.T) {
			nodes, err := emitDoubleElimination(deDraw(count))
			if err != nil {
				t.Fatalf("emitDoubleElimination: %v", err)
			}

			positions := index(nodes)
			if len(positions) != len(nodes) {
				t.Fatalf("%d nodes but %d distinct refs", len(nodes), len(positions))
			}

			consumers := make(map[string]LocalRef, len(nodes)*2)
			for _, node := range nodes {
				for _, slot := range []Slot{node.Home, node.Away} {
					switch slot.Kind {
					case SourceEntry, SourceBye:
						continue
					case SourceWinnerOf, SourceLoserOf:
					default:
						t.Fatalf("%s: slot kind %s", node.Ref, slot.Kind)
					}
					if _, ok := positions[slot.Src]; !ok {
						t.Fatalf("%s: dangling reference to %s", node.Ref, slot.Src)
					}
					if slot.Src == node.Ref {
						t.Fatalf("%s: references itself", node.Ref)
					}
					key := slot.Src.String() + "/" + slot.Kind.String()
					if previous, taken := consumers[key]; taken {
						t.Fatalf("%s of %s consumed by both %s and %s",
							slot.Kind, slot.Src, previous, node.Ref)
					}
					consumers[key] = node.Ref
				}
				if node.Activation == ActivationUnconditional && !node.ActSrc.zero() {
					t.Fatalf("%s: unconditional yet names %s", node.Ref, node.ActSrc)
				}
				if node.Activation != ActivationUnconditional {
					if node.ActSrc.zero() {
						t.Fatalf("%s: conditional with no activation source", node.Ref)
					}
					if _, ok := positions[node.ActSrc]; !ok {
						t.Fatalf("%s: activation source %s does not exist", node.Ref, node.ActSrc)
					}
				}
			}

			// Acyclicity, the Go side of match_slots_acyclic_chk. Rank tolerates
			// byes, so it can run on the raw output.
			ranked := Rank(Graph{Format: DoubleElimination, Nodes: nodes})
			ranks := index(ranked.Nodes)
			for _, node := range ranked.Nodes {
				for _, slot := range []Slot{node.Home, node.Away} {
					if slot.Kind != SourceWinnerOf && slot.Kind != SourceLoserOf {
						continue
					}
					if source := ranked.Nodes[ranks[slot.Src]]; source.Rank >= node.Rank {
						t.Fatalf("%s (rank %d) depends on %s (rank %d)",
							node.Ref, node.Rank, source.Ref, source.Rank)
					}
				}
			}
		})
	}
}

// TestDoubleEliminationNoDuplicateSlotPairing checks that no two matches in the
// same bracket and round read from the same pair of sources, which would mean
// the same two players were scheduled twice.
func TestDoubleEliminationNoDuplicateSlotPairing(t *testing.T) {
	for _, count := range deSizes {
		t.Run(fmt.Sprintf("n=%d", count), func(t *testing.T) {
			graph := deEmit(t, count)
			seen := make(map[string]LocalRef, len(graph.Nodes))
			for _, node := range graph.Nodes {
				pair := dePairKey(deSlotKey(node.Home), deSlotKey(node.Away))
				key := fmt.Sprintf("%s/R%d|%s|%s", node.Ref.Bracket, node.Ref.Round, pair[0], pair[1])
				if previous, taken := seen[key]; taken {
					t.Fatalf("%s repeats the pairing already scheduled as %s", node.Ref, previous)
				}
				seen[key] = node.Ref
			}
		})
	}
}

// ---------------------------------------------------------------------------
// the drop mapping
// ---------------------------------------------------------------------------

// TestDoubleEliminationDropMapping reads the mapping back out of a graph with no
// byes in it, so the emitted edges rather than the helper are what is checked.
func TestDoubleEliminationDropMapping(t *testing.T) {
	for rounds := 2; rounds <= 7; rounds++ {
		size := 1 << rounds
		t.Run(fmt.Sprintf("n=%d", size), func(t *testing.T) {
			graph := deEmit(t, size)

			for number := 1; number <= size/4; number++ {
				node := deNode(t, graph, deLosersRef(1, number))
				if want := loserSlot(deWinnersRef(1, 2*number-1)); node.Home != want {
					t.Fatalf("%s home = %+v, want %+v", node.Ref, node.Home, want)
				}
				if want := loserSlot(deWinnersRef(1, 2*number)); node.Away != want {
					t.Fatalf("%s away = %+v, want %+v", node.Ref, node.Away, want)
				}
			}

			for drop := 1; drop <= rounds-1; drop++ {
				width := size >> (drop + 1)
				used := make([]int, width+1)
				for number := 1; number <= width; number++ {
					node := deNode(t, graph, deLosersRef(2*drop, number))
					if want := winnerSlot(deLosersRef(2*drop-1, number)); node.Home != want {
						t.Fatalf("%s home = %+v, want %+v", node.Ref, node.Home, want)
					}
					if node.Away.Kind != SourceLoserOf ||
						node.Away.Src.Bracket != BracketWinners ||
						node.Away.Src.Round != drop+1 {
						t.Fatalf("%s away = %+v, want the loser of winners round %d",
							node.Ref, node.Away, drop+1)
					}
					target := node.Away.Src.Number
					if target < 1 || target > width {
						t.Fatalf("%s drops from winners match %d, outside 1..%d",
							node.Ref, target, width)
					}
					used[target]++

					// The property the mapping exists for, at the index level:
					// the drop must not land on the losers match that the
					// winners round it came from feeds into directly.
					if width > 1 && drop == 1 && target == number {
						t.Fatalf("%s takes the drop from the winners match fed by its own pool", node.Ref)
					}
				}
				for target := 1; target <= width; target++ {
					if used[target] != 1 {
						t.Fatalf("winners round %d match %d drops into %d losers matches, want 1",
							drop+1, target, used[target])
					}
				}
			}

			for drop := 1; drop <= rounds-2; drop++ {
				width := size >> (drop + 1)
				for number := 1; number <= width/2; number++ {
					node := deNode(t, graph, deLosersRef(2*drop+1, number))
					if want := winnerSlot(deLosersRef(2*drop, 2*number-1)); node.Home != want {
						t.Fatalf("%s home = %+v, want %+v", node.Ref, node.Home, want)
					}
					if want := winnerSlot(deLosersRef(2*drop, 2*number)); node.Away != want {
						t.Fatalf("%s away = %+v, want %+v", node.Ref, node.Away, want)
					}
				}
			}
		})
	}
}

// TestDoubleEliminationDropMappingSpotCheck writes out the 16 entrant mapping by
// hand. Reversal on the first drop, identity on the second, and the third has
// only one match so both agree.
func TestDoubleEliminationDropMappingSpotCheck(t *testing.T) {
	graph := deEmit(t, 16)
	expected := map[LocalRef]LocalRef{
		deLosersRef(2, 1): deWinnersRef(2, 4),
		deLosersRef(2, 2): deWinnersRef(2, 3),
		deLosersRef(2, 3): deWinnersRef(2, 2),
		deLosersRef(2, 4): deWinnersRef(2, 1),
		deLosersRef(4, 1): deWinnersRef(3, 1),
		deLosersRef(4, 2): deWinnersRef(3, 2),
		deLosersRef(6, 1): deWinnersRef(4, 1),
	}
	for ref, source := range expected {
		node := deNode(t, graph, ref)
		if want := loserSlot(source); node.Away != want {
			t.Fatalf("%s away = %+v, want %+v", ref, node.Away, want)
		}
	}
}

// ---------------------------------------------------------------------------
// grand final and bracket reset
// ---------------------------------------------------------------------------

func TestDoubleEliminationGrandFinalAndReset(t *testing.T) {
	for _, count := range deSizes {
		t.Run(fmt.Sprintf("n=%d", count), func(t *testing.T) {
			graph := deEmit(t, count)
			rounds := deRoundCount(nextPowerOfTwo(count))

			first := deNode(t, graph, deFinalRef(1))
			if want := winnerSlot(deWinnersRef(rounds, 1)); first.Home != want {
				t.Fatalf("grand final home = %+v, want %+v", first.Home, want)
			}
			if rounds == 1 {
				if want := loserSlot(deWinnersRef(1, 1)); first.Away != want {
					t.Fatalf("grand final away = %+v, want %+v", first.Away, want)
				}
			} else if want := winnerSlot(deLosersRef(2*rounds-2, 1)); first.Away != want {
				t.Fatalf("grand final away = %+v, want %+v", first.Away, want)
			}
			if first.Activation != ActivationUnconditional || !first.ActSrc.zero() {
				t.Fatalf("grand final activation = %q %s", first.Activation, first.ActSrc)
			}

			reset := deNode(t, graph, deFinalRef(2))
			if reset.Activation != ActivationIfAwayWins {
				t.Fatalf("reset activation = %q, want %q", reset.Activation, ActivationIfAwayWins)
			}
			if reset.ActSrc != first.Ref {
				t.Fatalf("reset activation source = %s, want %s", reset.ActSrc, first.Ref)
			}
			if want := loserSlot(first.Ref); reset.Home != want {
				t.Fatalf("reset home = %+v, want %+v", reset.Home, want)
			}
			if want := winnerSlot(first.Ref); reset.Away != want {
				t.Fatalf("reset away = %+v, want %+v", reset.Away, want)
			}

			// match_slots_one_consumer_uidx for the two matches that make the
			// index interesting: nothing else may read either outcome of the
			// first grand final, and the winners final's loser is free for the
			// grand final to take only when there is no losers bracket.
			for _, node := range graph.Nodes {
				if node.Ref == reset.Ref {
					continue
				}
				for _, slot := range []Slot{node.Home, node.Away} {
					if slot.Src == first.Ref {
						t.Fatalf("%s also consumes %s of the grand final", node.Ref, slot.Kind)
					}
				}
			}
		})
	}
}

// ---------------------------------------------------------------------------
// determinism
// ---------------------------------------------------------------------------

func TestDoubleEliminationDeterministic(t *testing.T) {
	for _, count := range []int{2, 3, 5, 6, 7, 11, 13, 16, 23, 31, 33, 64, 100} {
		t.Run(fmt.Sprintf("n=%d", count), func(t *testing.T) {
			in := deDraw(count)
			first, err := Emit(in)
			if err != nil {
				t.Fatalf("Emit: %v", err)
			}
			for run := 0; run < 5; run++ {
				again, err := Emit(deDraw(count))
				if err != nil {
					t.Fatalf("Emit run %d: %v", run, err)
				}
				if again.Fingerprint != first.Fingerprint {
					t.Fatalf("run %d fingerprint %x, first %x", run, again.Fingerprint, first.Fingerprint)
				}
				if len(again.Nodes) != len(first.Nodes) {
					t.Fatalf("run %d has %d nodes, first has %d", run, len(again.Nodes), len(first.Nodes))
				}
				for position := range first.Nodes {
					if again.Nodes[position] != first.Nodes[position] {
						t.Fatalf("run %d node %d = %+v, first = %+v",
							run, position, again.Nodes[position], first.Nodes[position])
					}
				}
			}
		})
	}
}

// TestDoubleEliminationDrawOrderIsTheDraw makes sure the emitter treats
// in.Entries as given. Reversing the vector must move players, or something is
// reordering or re-seeding behind the caller's back.
func TestDoubleEliminationDrawOrderIsTheDraw(t *testing.T) {
	forward := deDraw(8)
	backward := DrawInput{Format: DoubleElimination, Entries: make([]DrawEntry, len(forward.Entries))}
	for position, entry := range forward.Entries {
		backward.Entries[len(forward.Entries)-1-position] = entry
	}

	first, err := Emit(forward)
	if err != nil {
		t.Fatalf("Emit forward: %v", err)
	}
	second, err := Emit(backward)
	if err != nil {
		t.Fatalf("Emit backward: %v", err)
	}
	if first.Fingerprint == second.Fingerprint {
		t.Fatal("reversing the draw produced the same graph, so the order is being ignored")
	}

	opener := deNode(t, first, deWinnersRef(1, 1))
	if opener.Home.EntryID != forward.Entries[0].EntryID {
		t.Fatalf("first match home = %q, want the first entry %q",
			opener.Home.EntryID, forward.Entries[0].EntryID)
	}
}

// ---------------------------------------------------------------------------
// simulation
// ---------------------------------------------------------------------------

type deOutcome struct {
	ref           LocalRef
	home, away    string
	winner, loser string
}

// deRand is a fixed linear congruential generator. Tests need varied outcome
// vectors but must stay reproducible, so this is seeded per subtest rather than
// drawn from math/rand.
type deRand struct{ state uint64 }

func (r *deRand) homeWins() bool {
	r.state = r.state*6364136223846793005 + 1442695040888963407
	return (r.state>>33)&1 == 0
}

func deResolve(played map[LocalRef]deOutcome, slot Slot) (string, bool) {
	switch slot.Kind {
	case SourceEntry:
		return slot.EntryID, slot.EntryID != ""
	case SourceWinnerOf:
		outcome, ok := played[slot.Src]
		return outcome.winner, ok
	case SourceLoserOf:
		outcome, ok := played[slot.Src]
		return outcome.loser, ok
	}
	return "", false
}

// deSimulate plays the whole graph in rank order, which is a topological order
// because every edge points at a strictly lower rank. A conditional match is
// skipped unless its source resolved the way its activation rule requires.
func deSimulate(t *testing.T, graph Graph, seed uint64) []deOutcome {
	t.Helper()

	nodes := append([]Node(nil), graph.Nodes...)
	sort.SliceStable(nodes, func(i, j int) bool {
		if nodes[i].Rank != nodes[j].Rank {
			return nodes[i].Rank < nodes[j].Rank
		}
		return nodes[i].Ref.less(nodes[j].Ref)
	})

	rng := deRand{state: seed*0x9E3779B97F4A7C15 + 0x1234567}
	played := make(map[LocalRef]deOutcome, len(nodes))
	order := make([]deOutcome, 0, len(nodes))

	for _, node := range nodes {
		if node.Activation == ActivationIfAwayWins {
			source, ok := played[node.ActSrc]
			if !ok || source.winner != source.away {
				continue
			}
		}
		home, ok := deResolve(played, node.Home)
		if !ok || home == "" {
			t.Fatalf("%s: home slot %+v did not resolve", node.Ref, node.Home)
		}
		away, ok := deResolve(played, node.Away)
		if !ok || away == "" {
			t.Fatalf("%s: away slot %+v did not resolve", node.Ref, node.Away)
		}
		if home == away {
			t.Fatalf("%s: %s is scheduled against itself", node.Ref, home)
		}
		outcome := deOutcome{ref: node.Ref, home: home, away: away, winner: home, loser: away}
		if !rng.homeWins() {
			outcome.winner, outcome.loser = away, home
		}
		played[node.Ref] = outcome
		order = append(order, outcome)
	}
	return order
}

// TestDoubleEliminationSimulation plays every field size from 2 to 48 under
// several outcome vectors and checks the properties that only appear once
// players are moving: two losses eliminates you, nobody is scheduled twice in a
// round, and the immediate rematch the drop mapping exists to prevent does not
// occur.
func TestDoubleEliminationSimulation(t *testing.T) {
	sizes := make([]int, 0, 52)
	for count := 2; count <= 48; count++ {
		sizes = append(sizes, count)
	}
	sizes = append(sizes, 64, 65, 100, 128)

	for _, count := range sizes {
		for seed := uint64(1); seed <= 6; seed++ {
			t.Run(fmt.Sprintf("n=%d/seed=%d", count, seed), func(t *testing.T) {
				graph := deEmit(t, count)
				results := deSimulate(t, graph, seed)
				deCheckSimulation(t, count, graph, results)
			})
		}
	}
}

func deCheckSimulation(t *testing.T, count int, graph Graph, results []deOutcome) {
	t.Helper()

	byRef := make(map[LocalRef]deOutcome, len(results))
	losses := make(map[string]int, count)
	appearances := make(map[string]int, count)
	perRoundEntry := make(map[string]LocalRef, len(results)*2)
	perRoundPair := make(map[string]LocalRef, len(results))
	metInWinners := make(map[[2]string]int, len(results))

	for _, outcome := range results {
		byRef[outcome.ref] = outcome
		losses[outcome.loser]++
		appearances[outcome.home]++
		appearances[outcome.away]++

		roundKey := fmt.Sprintf("%s/R%d", outcome.ref.Bracket, outcome.ref.Round)
		for _, player := range []string{outcome.home, outcome.away} {
			key := roundKey + "|" + player
			if previous, taken := perRoundEntry[key]; taken {
				t.Fatalf("%s plays both %s and %s in the same round", player, previous, outcome.ref)
			}
			perRoundEntry[key] = outcome.ref
		}
		pair := dePairKey(outcome.home, outcome.away)
		pairKey := roundKey + "|" + pair[0] + "|" + pair[1]
		if previous, taken := perRoundPair[pairKey]; taken {
			t.Fatalf("%s repeats the pairing played in %s", outcome.ref, previous)
		}
		perRoundPair[pairKey] = outcome.ref

		if outcome.ref.Bracket == BracketWinners {
			if previous, taken := metInWinners[pair]; taken {
				t.Fatalf("%s and %s meet twice in the winners bracket, rounds %d and %d",
					pair[0], pair[1], previous, outcome.ref.Round)
			}
			metInWinners[pair] = outcome.ref.Round
		}
	}

	// Everyone plays, and everyone but the champion is eliminated on two losses.
	if len(appearances) != count {
		t.Fatalf("%d entrants played, want %d", len(appearances), count)
	}

	resetOutcome, resetPlayed := byRef[deFinalRef(2)]
	firstFinal, ok := byRef[deFinalRef(1)]
	if !ok {
		t.Fatal("the grand final was never played")
	}
	champion := firstFinal.winner
	if resetPlayed {
		champion = resetOutcome.winner
		if firstFinal.winner != firstFinal.away {
			t.Fatal("the reset was played even though the winners bracket finalist won the grand final")
		}
	} else if firstFinal.winner == firstFinal.away {
		t.Fatal("the losers bracket finalist won the grand final but no reset was played")
	}

	wantMatches := 2*count - 2
	if resetPlayed {
		wantMatches = 2*count - 1
	}
	if len(results) != wantMatches {
		t.Fatalf("%d matches played, want %d (reset played = %v)", len(results), wantMatches, resetPlayed)
	}

	for _, outcome := range results {
		for _, player := range []string{outcome.home, outcome.away} {
			if player != champion && losses[player] != 2 {
				t.Fatalf("%s finished with %d losses, want 2", player, losses[player])
			}
		}
	}
	wantChampionLosses := 0
	if resetPlayed {
		wantChampionLosses = 1
	}
	if losses[champion] != wantChampionLosses {
		t.Fatalf("champion %s has %d losses, want %d", champion, losses[champion], wantChampionLosses)
	}

	// The immediate rematch. A player dropping out of winners round drop+1 must
	// not meet, in losers round 2*drop, the player they beat in winners round
	// drop. The exemption is a major round with a single match, where the format
	// leaves no other placement; that is always the losers final, and also
	// round 2 of a four entrant draw.
	rounds := deRoundCount(nextPowerOfTwo(count))
	for _, outcome := range results {
		if outcome.ref.Bracket != BracketLosers || outcome.ref.Round%2 != 0 {
			continue
		}
		drop := outcome.ref.Round / 2
		if 1<<(rounds-1-drop) < 2 {
			continue
		}
		if met, ok := metInWinners[dePairKey(outcome.home, outcome.away)]; ok && met == drop {
			t.Fatalf("%s is an immediate rematch of winners round %d between %s and %s",
				outcome.ref, drop, outcome.home, outcome.away)
		}
	}
}

// TestDoubleEliminationSimulationDeterministic makes sure the simulation itself
// is reproducible, so a failure above can be reproduced from the seed alone.
func TestDoubleEliminationSimulationDeterministic(t *testing.T) {
	graph := deEmit(t, 23)
	first := deSimulate(t, graph, 7)
	second := deSimulate(t, graph, 7)
	if len(first) != len(second) {
		t.Fatalf("%d outcomes then %d", len(first), len(second))
	}
	for position := range first {
		if first[position] != second[position] {
			t.Fatalf("outcome %d differs: %+v then %+v", position, first[position], second[position])
		}
	}
}

// ---------------------------------------------------------------------------
// input handling
// ---------------------------------------------------------------------------

func TestDoubleEliminationRejectsTinyField(t *testing.T) {
	if _, err := emitDoubleElimination(DrawInput{Format: DoubleElimination}); err != ErrTooFewEntries {
		t.Fatalf("empty draw: err = %v, want %v", err, ErrTooFewEntries)
	}
	if _, err := Emit(DrawInput{Format: DoubleElimination, Entries: deEntries(1)}); err != ErrTooFewEntries {
		t.Fatalf("one entrant: err = %v, want %v", err, ErrTooFewEntries)
	}
}

func TestDoubleEliminationIgnoresIrrelevantConfig(t *testing.T) {
	// ThirdPlace, GroupCount and DoubleRoundRobin belong to the other formats.
	// A double elimination draw must not grow a bronze match or a group key.
	plain, err := Emit(deDraw(9))
	if err != nil {
		t.Fatalf("Emit: %v", err)
	}
	loud := deDraw(9)
	loud.Config = Config{BestOf: 5, ThirdPlace: true, GroupCount: 4, DoubleRoundRobin: true}
	noisy, err := Emit(loud)
	if err != nil {
		t.Fatalf("Emit with config: %v", err)
	}
	if plain.Fingerprint != noisy.Fingerprint {
		t.Fatal("single elimination and round robin options changed the double elimination graph")
	}
	for _, node := range noisy.Nodes {
		if node.Ref.Bracket == BracketBronze {
			t.Fatalf("%s: double elimination emitted a bronze match", node.Ref)
		}
	}
}

// ---------------------------------------------------------------------------
// seeding
// ---------------------------------------------------------------------------
//
// The two tests below are the only ones in this file that pin WHERE the draw
// vector lands. Everything above constrains the shape of the graph, and a graph
// that seats the draw sequentially has exactly the same shape as one seeded by
// seedOrder: same match count, same edges, same ranks, same 2n-1, and it plays
// out under deSimulate identically. It is simply the wrong tournament, and
// without these two properties that substitution is invisible here.

// deOpeners reads, out of the raw emitter output, the winners round 1 match each
// entrant is seated in.
func deOpeners(t *testing.T, nodes []Node) map[string]int {
	t.Helper()
	seats := make(map[string]int)
	for _, node := range nodes {
		if node.Ref.Bracket != BracketWinners || node.Ref.Round != 1 {
			continue
		}
		for _, slot := range []Slot{node.Home, node.Away} {
			if slot.Kind != SourceEntry {
				continue
			}
			if previous, taken := seats[slot.EntryID]; taken {
				t.Fatalf("%s is seated in winners round 1 matches %d and %d",
					slot.EntryID, previous, node.Ref.Number)
			}
			seats[slot.EntryID] = node.Ref.Number
		}
	}
	return seats
}

// TestDoubleEliminationByesGoToTheTopSeeds is the half of the seeding contract
// that only appears when the field is not a power of two. seedOrder puts the
// surplus positions opposite the low seeds, so for a field of n in a bracket of
// size, exactly the first size-n draw positions sit out the first round.
//
// Read on the raw output rather than the pruned graph, because a bye is exactly
// what Prune deletes: after pruning "had a bye" is only recoverable as "is not
// named by any winners round 1 match", which is a weaker statement.
func TestDoubleEliminationByesGoToTheTopSeeds(t *testing.T) {
	for _, count := range deSizes {
		t.Run(fmt.Sprintf("n=%d", count), func(t *testing.T) {
			nodes, err := emitDoubleElimination(deDraw(count))
			if err != nil {
				t.Fatalf("emitDoubleElimination: %v", err)
			}
			byes := nextPowerOfTwo(count) - count

			opponents := make(map[string]Slot, count)
			for _, node := range nodes {
				if node.Ref.Bracket != BracketWinners || node.Ref.Round != 1 {
					continue
				}
				if node.Home.Kind == SourceEntry {
					opponents[node.Home.EntryID] = node.Away
				}
				if node.Away.Kind == SourceEntry {
					opponents[node.Away.EntryID] = node.Home
				}
			}
			if len(opponents) != count {
				t.Fatalf("%d entrants seated in winners round 1, want %d", len(opponents), count)
			}

			for position, entry := range deEntries(count) {
				opponent, seated := opponents[entry.EntryID]
				if !seated {
					t.Fatalf("%s is not seated in winners round 1", entry.EntryID)
				}
				got := opponent.Kind == SourceBye
				want := position < byes
				if got != want {
					t.Fatalf("draw position %d has a first round bye = %v, want %v "+
						"(%d entrants in a bracket of %d, so the top %d sit out)",
						position+1, got, want, count, nextPowerOfTwo(count), byes)
				}
			}
		})
	}
}

// TestDoubleEliminationSeedsAreSpreadAcrossTheBracket is the other half: the
// draw folds, so the strongest entrants are kept apart for as long as the
// bracket allows.
//
// Winners round r has 2^(k-r) matches, and round 1 match m feeds round r match
// ceil(m / 2^(r-1)). The property is that the top 2^(k-r) draw positions reach
// 2^(k-r) DIFFERENT round r matches, one each, so none of them can meet before
// round r. At r = k-1 that is the familiar statement that draw positions 1 and 2
// cannot meet before the winners final.
func TestDoubleEliminationSeedsAreSpreadAcrossTheBracket(t *testing.T) {
	for _, count := range deSizes {
		t.Run(fmt.Sprintf("n=%d", count), func(t *testing.T) {
			nodes, err := emitDoubleElimination(deDraw(count))
			if err != nil {
				t.Fatalf("emitDoubleElimination: %v", err)
			}
			size := nextPowerOfTwo(count)
			rounds := deRoundCount(size)
			seats := deOpeners(t, nodes)
			entries := deEntries(count)

			for round := 1; round <= rounds; round++ {
				top := size >> round
				if top > count {
					top = count
				}
				reached := make(map[int]string, top)
				for position := 0; position < top; position++ {
					id := entries[position].EntryID
					opener, seated := seats[id]
					if !seated {
						t.Fatalf("%s is not seated in winners round 1", id)
					}
					stride := 1 << (round - 1)
					reaches := (opener + stride - 1) / stride
					if previous, taken := reached[reaches]; taken {
						t.Fatalf("draw positions %s and %s both reach winners round %d match %d, "+
							"so two of the top %d seeds can meet before round %d",
							previous, id, round, reaches, top, round)
					}
					reached[reaches] = id
				}
			}
		})
	}
}
